export const PDF_OPTION_PRESET_FILE_PATH = process.env.HCPDF_PDF_OPTION_PRESET_FILE_PATH ?? './presets/default'
export const DEFAULT_PDF_OPTION_PRESET_NAME = process.env.HCPDF_DEFAULT_PDF_OPTION_PRESET_NAME ?? 'A4'
